# Generated by Django 3.0.5 on 2020-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
